language: node_js
node_js:
  - "9"
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - webdriver-manager update
  - npm run dist
  - cp jsgantt.js docs/ && cp src/jsgantt.css docs/ && cd docs && http-server &  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc

before_install:
  - npm install -g http-server browserify webdriver-manager
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install
  - ./node_modules/protractor/bin/webdriver-manager update --versions.chrome 2.35
  - webdriver-manager update
  - node node_modules/protractor/bin/webdriver-manager update
  - node_modules/protractor/bin/webdriver-manager update